### ISSUE TITLE
Dahboard only gives ab lank page 

### ISSUE THREAD

**Issue by rollanders** [nextcloud/dashboard#77] opened 2020-10-12 13:54 UTC
I only get a white page in Dashboard. Only my avatar is visible and a red dot for Notifications. The menu (to choose other apps) is not visible but can be accessed by cliqing on their expected location in the page.  See photo
Same result in Edge, Chrome and Firefox on Windows 10. NC 20.0.0, Dashboard 7.0.0 Server Ubuntu 18.0.4. Nginx
 
![Dashboard](https://user-images.githubusercontent.com/36486009/95754738-c63cad80-0ca3-11eb-8f44-0cbf05f92157.jpg)

**Comment by Mikescops** [comment] 2020-10-12 16:04
Duplicate of #74

**Comment by Mikescops** [comment] 2020-10-12 16:13
This is unrelated to this project, this issue should be addressed in nextcloud/server

This was fixed here: https://github.com/nextcloud/server/issues/23163

**Closed by Mikescops** 2020-10-12 16:13 UTC
Labels: duplicate, invalid
